apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
      - ./infra/k8s-dev/*
build:
  local:
    push: false
  artifacts:
  
    - image: sahal1/fusion
      context: fusion
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.jsx"
            dest: .
          - src: "src/**/*.js"
            dest: .
          - src: "src/**/*.css"
            dest: .

    - image: sahal1/auth
      context: authentication
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "**/*.py"
            dest: .

    - image: sahal1/admin
      context: admin
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "**/*.py"
            dest: .
            
    - image: sahal1/server
      context: server
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "**/*.py"
            dest: .
    
    
    